### PR TITLE
feat(ui): Add mention reply indicator

### PR DESCRIPTION
**Pull request by stationaryStation**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

This PR should close the following issue: `issue: reply pings do not include '@'`

This is my first contribution to revolt so any feedback about code quality would be helpful.

### CODE REVIEW

**Comment by Rexogamer** [comment]
Looks like you accidentally changed the assets submodule?

**Comment by ghost** [comment]
Weird, VSCode didn't tell me about changing the assets submodule. Maybe it did because I had the dev server open?

**Comment by ghost** [comment]
Reverting to the latest commit shows me this on vscode
image

**Comment by ghost** [comment]
I can't really find what is wrong with my fork so I will retry the pr on a new fork

**Pull request closed without merging**
